Fix debounce on click.redditmail.com
brave/adblock-lists pull request #1112
Opened 2023-03-20 22:56 UTC by ryanbr

Fixes Debounce of `https://click.redditmail.com/CL0/https:%2F%2Fwww.reddit.com%2Fr%2FCryptoCurrency%2Fcomments%2F11uycvy%2Fcoinbase_is_looking_for_a_new_overseas%2F%3F$deep_link=true%26correlation_id=3fa0d687-770e-46d1-b901-f66d87c1f9f2%26post_fullname=t3_11uycvy%26post_index=2%26ref=email_digest%26ref_campaign=email_digest%26ref_source=email%26utm_content=post_title/1/01000186f87ebc5b-bd2b745a-9ccd-43c3-b088-013e454697ca-000000/AEzOEmcrhWz3Rlpr0tnYU2bQWItWlElct4rU3qgL8XU=292`

2023-03-20 23:02 UTC, fmarier requested changes
The param is not right because there's some extra stuff at the end of the URL that doesn't end up on the final page: `/1/01000186f87ebc5b-bd2b745a-9ccd-43c3-b088-013e454697ca-000000/AEzOEmcrhWz3Rlpr0tnYU2bQWItWlElct4rU3qgL8XU=292`.

So we probably need something like: `^/CL0/([^/]+)$` (not tested)

2023-03-20 23:04 UTC, fmarier commented
Also, we're technically not fixing the debounce since we're not currently debouncing these URLs at all. We're _adding_ a debounce instead.

2023-03-20 23:17 UTC, ryanbr commented
![regex-reddit](https://user-images.githubusercontent.com/1659004/226485823-94525a08-98f0-4369-a98c-e8b48caf8a59.jpg)

using regex101, I tested the regex `^/CL0/([^/]+)$` (didn't work).

2023-03-20 23:20 UTC, fmarier commented
> using regex101, I tested the regex `^/CL0/([^/]+)$` (didn't work).

Right, it needs to capture the extra stuff at the end, so maybe `^/CL0/([^/]+)/.*$`?

2023-03-20 23:24 UTC, ryanbr commented
Okay, that works. can update the PR

2023-03-21 00:12 UTC, fmarier approved these changes

2023-03-21 01:09 UTC, merged